FROM python:3.9 
WORKDIR /ca1 # This is the same as 'cd' on a terminal and it can also create folders too
COPY index.html /
CMD python3 -m http.server 8080 # I used this to provide the commands and arguements to execute the container

